
known_hosts_path = "/home/user/.ssh/known_hosts"
log_file = "/home/user/honeypot-healthcheck/healthcheck.log"

[cowrie]
	hosts = [
		"localhost",
		"192.168.8.1"
	]

	port = 2222
	user = "root"
	password = "1234"


